# Generated by Django 3.2.8 on 2021-10-17 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('ShippingAddressId', models.AutoField(primary_key=True, serialize=False)),
                ('ShippingAddressLine1', models.CharField(max_length=200)),
                ('ShippingAddressLine2', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('ShippingAddressState', models.CharField(max_length=50)),
                ('ShippingAddressCountry', models.CharField(max_length=50)),
                ('ShippingAddressPinCode', models.CharField(max_length=10)),
                ('ShippingAddressPhone', models.BigIntegerField()),
                ('ShippingAddressCustomerId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ShippingAddress',
                'verbose_name_plural': 'ShippingAddresses',
            },
        ),
    ]
