# Generated by Django 3.2.8 on 2021-10-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_shippingaddress_shippingname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='ShippingName',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
