# Generated by Django 3.2.8 on 2021-10-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_shippingaddress_shippingname'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='ShippingAddressCity',
            field=models.CharField(default='None', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='ShippingAddressCountry',
            field=models.CharField(default='India', max_length=50),
        ),
    ]
