# Generated by Django 3.2.8 on 2021-10-17 20:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteMetaData',
            fields=[
                ('SiteId', models.AutoField(primary_key=True, serialize=False)),
                ('SiteTitle', models.CharField(max_length=100)),
                ('SiteFlatShipping', models.BooleanField(default=False)),
                ('SiteFlatShippingLimit', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('SiteIsCODAllowed', models.BooleanField(blank=True, default=True)),
                ('SiteAddressLine1', models.CharField(max_length=100)),
                ('SiteAddressLine2', models.CharField(max_length=100)),
                ('SiteShippingAddressState', models.CharField(max_length=50)),
                ('SiteShippingAddressCountry', models.CharField(max_length=50)),
                ('SiteShippingAddressPincode', models.CharField(max_length=10)),
                ('SiteTermsConditions', models.CharField(max_length=1000)),
                ('SiteFacebookLink', models.URLField(blank=True, default=None, null=True)),
                ('SiteTwitterLink', models.URLField(blank=True, default=None, null=True)),
                ('SitePhoneList', models.CharField(max_length=200)),
                ('SiteProducts', models.ManyToManyField(blank=True, to='product.Product')),
            ],
            options={
                'verbose_name': 'SiteMetaData',
                'verbose_name_plural': 'SiteMetaData',
            },
        ),
    ]
