# Generated by Django 3.2.8 on 2021-10-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_meta', '0002_fileupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='FileUrl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
