# Generated by Django 3.2.8 on 2021-10-17 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_tax_taxslug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='TaxSlug',
            field=models.SlugField(default=None),
        ),
    ]
