# Generated by Django 3.2.8 on 2021-10-26 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_productprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='CategoryFeaturedImageFile',
            field=models.FileField(blank=True, default=None, null=True, upload_to='static/category/'),
        ),
    ]
