# Generated by Django 3.2.8 on 2021-10-26 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_category_categoryfeaturedimagefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='CategoryFeaturedImageFile',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
