# Generated by Django 3.2.8 on 2021-10-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_category_categoryfeaturedimagefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='CategoryImageUrl',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ProductImageUrl',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
