# Generated by Django 3.2.8 on 2021-10-26 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20211026_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ProductCategories',
        ),
        migrations.AddField(
            model_name='product',
            name='ProductCategories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.category'),
        ),
    ]
