# Generated by Django 3.2.8 on 2021-10-27 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20211026_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ProductTags',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='product.Tag'),
        ),
    ]
