# Generated by Django 3.2.8 on 2021-10-27 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_product_producttags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ProductTags',
        ),
        migrations.AddField(
            model_name='product',
            name='ProductTags',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
