# Generated by Django 3.2.8 on 2021-10-17 20:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('OrderId', models.AutoField(primary_key=True, serialize=False)),
                ('OrderShippingRate', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('OrderFlatShipping', models.BooleanField(blank=True, default=False)),
                ('OrderDateTime', models.DateTimeField(auto_now_add=True)),
                ('OrderStatus', models.CharField(choices=[('PROCESSING', 'PROCESSING'), ('CONFIRMED', 'CONFIRMED'), ('PENDING', 'PENDING'), ('CANCELLED', 'CANCELLED'), ('SHIPPED', 'SHIPPED')], default='PROCESSING', max_length=50)),
                ('OrderTotal', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('OrderCustomerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('OrderShippingAddress', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.shippingaddress')),
            ],
            options={
                'ordering': ['OrderDateTime'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductQuantity', models.PositiveIntegerField(default=0)),
                ('ProductTotalCost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('ProductCustomizableImage', models.ImageField(blank=True, default=None, null=True, upload_to='static/order/')),
                ('ProductCustomizableText', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('OrderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('ProductId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'verbose_name': 'OrderItem',
            },
        ),
    ]
