# Generated by Django 3.2.8 on 2021-10-24 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20211019_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='OrderTrackingId',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
